typography_spectrum: 0.9369563574437052
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6029493522364646
  lightness: 0.12702064123004675
  saturation: 0.23119887430220842
  rhythmicContrast: 0.31696593249216676
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6330914460122585
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Millennial Market Consulting, LLC'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact
    id: 28dca970-818c-4cab-a357-1bbfb512505e
    type: content
favicon: null
purpose: []
